const filesArray = [
  [
    "./Economy and Politics/BengaluruTrafficSolution_Gamification_Probability.html",
    "./Economy and Politics/Corruption1_IslamicEmpire.html",
    "./Economy and Politics/Corruption2_DrAmbedkar_RBI_Solution.html",
    "./Economy and Politics/Corruption3_Anna_Kejriwal.html",
    "./Economy and Politics/DrAmbedkarWorkerRights.html",
    "./Economy and Politics/Gandhi.html",
    "./Economy and Politics/Hindu_In_Pakistan.html",
    "./Economy and Politics/IndiaChinaStatsCompare.html",
    "./Economy and Politics/IndianEconomy1.html",
    "./Economy and Politics/IndianEconomy2.html",
    "./Economy and Politics/IndianEconomy3.html",
    "./Economy and Politics/IPSPuranKrSuicide.html",
    "./Economy and Politics/Laddakh_SonamWangchuk.html",
    "./Economy and Politics/Nepal.html",
    "./Economy and Politics/Periyar.html",
    "./Economy and Politics/Reservation.html",
    "./Economy and Politics/RightToQuestionReligionBRGavai.html",
    "./Economy and Politics/SabidoForCasteReligionInclusion.html",
    "./Economy and Politics/SiliconValleyStartups1.html",
    "./Economy and Politics/SiliconValleyStartups2.html",
    "./Economy and Politics/SiliconValleyStartups3.html",
    "./Economy and Politics/Taliban.html",
    "./Economy and Politics/UrbanIndiaDataGenAI.html",
    "./Economy and Politics/WomenSafety.html",
  ],
  [
    "./Education and Career/90HourWork_CounterProductive.html",
    "./Education and Career/AIDataQuality.html",
    "./Education and Career/AI_ImpactOnResearch.html",
    "./Education and Career/AI_Limits_Literature.html",
    "./Education and Career/Astrology.html",
    "./Education and Career/Atheism.html",
    "./Education and Career/ChetanBhagatDebunk.html",
    "./Education and Career/ConventionalSuccess.html",
    "./Education and Career/CorporateWomenDay.html",
    "./Education and Career/HR_DEI_1.html",
    "./Education and Career/HR_DEI_2.html",
    "./Education and Career/IndianCoachingIndustry1.html",
    "./Education and Career/IndianCoachingIndustry2.html",
    "./Education and Career/IQ_Trauma_of_Marks.html",
    "./Education and Career/Maths.html",
    "./Education and Career/Mentorship.html",
    "./Education and Career/NobelPrizeAndEnglish.html",
    "./Education and Career/OshoOnIndia.html",
    "./Education and Career/Probability.html",
    "./Education and Career/Questioning_Success_Feminism.html",
    "./Education and Career/Ramayana.html",
    "./Education and Career/ReligionFromSource.html",
    "./Education and Career/ReligiousMenHinduHypocrisy.html",
    "./Education and Career/ReligiousMenIslamHypocrisy.html",
    "./Education and Career/Reservation.html",
    "./Education and Career/SalesSociology.html",
    "./Education and Career/Science_Vs_Religion.html",
    "./Education and Career/Shaktiman.html",
    "./Education and Career/TeachersDay.html",
    "./Education and Career/TherapyLimits.html",
    "./Education and Career/VC_SiliconValleyVsIndia.html",
    "./Education and Career/WhoAmI.html",
  ],
  [
    "./Relationships and Feminism/Dostoevsky_Idiot_Love.html",
    "./Relationships and Feminism/DowryUrbanIndia.html",
    "./Relationships and Feminism/EliteFeminismSubstack.html",
    "./Relationships and Feminism/InstagramNotReal.html",
    "./Relationships and Feminism/MarriageAnthropology1.html",
    "./Relationships and Feminism/MarriageAnthropology2.html",
    "./Relationships and Feminism/ParentalResponsibility.html",
    "./Relationships and Feminism/Parenting.html",
    "./Relationships and Feminism/Patriarchy_Motherhood.html",
    "./Relationships and Feminism/SigmaMalePatriarchy.html",
    "./Relationships and Feminism/UrbanEliteFeminism.html",
    "./Relationships and Feminism/UrbanIndiaFemaleEntitlement.html",
    "./Relationships and Feminism/UrbanIndiaMarriage.html",
    "./Relationships and Feminism/WhyFeminism.html",
  ],
];
